export const clientsDomain=Object.freeze({name:'clients',label:'Clientes'});
function normalizeText(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').replace(/[^a-z0-9]/g,'')}
function normalizePhone(value=''){const digits=String(value).replace(/\D/g,'');return digits.length>8?digits.slice(-9):digits}
function levenshtein(a,b){const rows=Array.from({length:b.length+1},(_,index)=>[index]);for(let column=0;column<=a.length;column++)rows[0][column]=column;for(let row=1;row<=b.length;row++)for(let column=1;column<=a.length;column++)rows[row][column]=b[row-1]===a[column-1]?rows[row-1][column-1]:Math.min(rows[row-1][column-1],rows[row][column-1],rows[row-1][column])+1;return rows[b.length][a.length]}
function nameSimilarity(a,b){const left=normalizeText(a),right=normalizeText(b);if(!left||!right)return 0;if(left===right)return 1;return 1-levenshtein(left,right)/Math.max(left.length,right.length)}
export function findSimilarClient(candidate,clients){const candidatePhone=normalizePhone(candidate.phone),candidateEmail=normalizeText(candidate.email);const matches=clients.map(client=>{const signals=[],similarity=nameSimilarity(candidate.name,client.name);if(similarity>=.78)signals.push(similarity===1?'mesmo nome':'nome muito parecido');if(candidatePhone&&candidatePhone.length>=8&&candidatePhone===normalizePhone(client.phone))signals.push('mesmo telefone');if(candidateEmail&&candidateEmail===normalizeText(client.email))signals.push('mesmo e-mail');const confidence=(signals.includes('mesmo e-mail')?1:0)+(signals.includes('mesmo telefone')?1:0)+similarity;return{client,signals,similarity,confidence}}).filter(match=>match.signals.length).sort((a,b)=>b.confidence-a.confidence);return matches[0]||null}
export function mergeClientData(existing,incoming){for(const field of ['segment','city','phone','email'])if(!existing[field]&&incoming[field])existing[field]=incoming[field];if(existing.status!=='Cliente'&&incoming.status==='Cliente')existing.status='Cliente';existing.mergedContacts=existing.mergedContacts||[];existing.mergedContacts.push({name:incoming.name,phone:incoming.phone||'',email:incoming.email||'',mergedAt:new Date().toISOString()});return existing}
export function validateClientRegistration(client,clients){const duplicate=findSimilarClient(client,clients);return duplicate?{valid:false,message:'Encontramos um cliente parecido.',duplicate}:{valid:true,message:'',duplicate:null}}
export function clientRelationshipCompleteness(client={}){const items=[['Contato principal',client.mainContact],['Decisor principal',client.decisionMaker],['Responsável pela conta',client.accountOwner],['Aderência ao ICP',client.icpFit&&client.icpFit!=='unknown'],['Objetivo do cliente',client.goal]];const done=items.filter(([,value])=>Boolean(String(value||'').trim())).length;return{done,total:items.length,percent:Math.round(done/items.length*100),items:items.map(([label,value])=>({label,done:Boolean(String(value||'').trim())}))}}
