import { ensureSchema, response } from '../../../../db/org';
import { decryptText } from '../../../../db/crypto';

export const dynamic='force-dynamic';
const encoder=new TextEncoder();
async function digest(value:string){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value)));return Array.from(bytes,byte=>byte.toString(16).padStart(2,'0')).join('')}
type RoomRow={token:string;payload:string;access_hash:string;expires_at:string;revoked_at:string|null;view_count:number;failed_attempts:number;locked_until:string|null};
function active(row:RoomRow|null){return Boolean(row&&!row.revoked_at&&new Date(row.expires_at).getTime()>Date.now())}

export async function GET(_request:Request,{params}:{params:Promise<{token:string}>}){const {token}=await params,db=await ensureSchema(),row=await db.prepare('SELECT token, expires_at, revoked_at, view_count FROM crm_deal_rooms WHERE token = ?').bind(token).first<RoomRow>();if(!row)return response({error:'not_found'},404);return response({active:active(row),expiresAt:row.expires_at,viewCount:Number(row.view_count||0)});}
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){const {token}=await params;let body:Record<string,unknown>;try{body=await request.json()}catch{return response({error:'invalid_json'},400)}const code=String(body.accessCode||'').replace(/\D/g,'').slice(0,6),db=await ensureSchema(),row=await db.prepare('SELECT token, payload, access_hash, expires_at, revoked_at, view_count, failed_attempts, locked_until FROM crm_deal_rooms WHERE token = ?').bind(token).first<RoomRow>();if(!active(row))return response({error:'room_unavailable'},410);if(row!.locked_until&&new Date(row!.locked_until).getTime()>Date.now())return response({error:'temporarily_locked'},429);if(code.length!==6||await digest(`${token}:${code}`)!==row!.access_hash){const attempts=Number(row!.failed_attempts||0)+1,lockedUntil=attempts>=5?new Date(Date.now()+15*60000).toISOString():null;await db.prepare('UPDATE crm_deal_rooms SET failed_attempts = ?, locked_until = ?, updated_at = ? WHERE token = ?').bind(attempts>=5?0:attempts,lockedUntil,new Date().toISOString(),token).run();return response({error:lockedUntil?'temporarily_locked':'invalid_code'},lockedUntil?429:403)}const now=new Date().toISOString();await db.prepare('UPDATE crm_deal_rooms SET view_count = view_count + 1, last_viewed_at = ?, updated_at = ?, failed_attempts = 0, locked_until = NULL WHERE token = ?').bind(now,now,token).run();return response({payload:JSON.parse(await decryptText(row!.payload)),viewCount:Number(row!.view_count||0)+1,expiresAt:row!.expires_at});}
